app:
  name: MyApp
secret:
  key: applicationProductionNotTest
redis:
  active: false

spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  rabbitmq:
    host: localhost
    port: 5672
    username: ouss
    password: password
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/Web}
    username: ${DB_USER:ouss}
    password: ${DB_PASSWORD:password}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update